version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: app-postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    restart: always
    container_name: app-django
    env_file: .env
    volumes:
      - /var/www/gavr/media:/var/www/gavr/media
      - /var/www/gavr/static:/var/www/gavr/static
    command:
      - /bin/sh
      - -c
      - |
        echo "fake migrations"
#        ./manage.py makemigrations
#        ./manage.py migrate
#        ./manage.py collectstatic --no-input
#        gunicorn -c gunicorn.py
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_HOST=db
    depends_on:
      - db
volumes:
  postgres_data:
  media:
  static:
