version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_HOST=${SQL_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: