version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: app-postgres
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    restart: always
    container_name: app-django
    env_file: .env
    volumes:
      - .:/app/
      - media:/app/media
    command:
      - /bin/sh
      - -c
      - |
        ./manage.py makemigrations
        ./manage.py migrate
        ./manage.py collectstatic --no-input
        ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8003:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - SQL_ENGINE=${SQL_ENGINE}
      - SQL_HOST=db
    depends_on:
      - db
volumes:
  postgres_data:
  media: