# Generated by Django 4.2.5 on 2023-10-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'Profile'},
        ),
        migrations.AlterField(
            model_name='profiles',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
